- auth-methods/api_key_auth.go
- auth-methods/api_key_auth_test.go
- auth-methods/auth_methods.go
- docs/swagger.yml
- docs/v1/api_auth_methods.md
- handlers/auth_method_handlers.go
- handlers/auth_method_handlers_test.go
- handlers/service_type_handlers_test.go
- servicetypes/service_type.go
- servicetypes/service_type_test.go
- stores/mock.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Update auth method to use service type uuid instead of service name.
updated tests, docs and swagger
> ARGO-1205 API AuthN: Authentication method - use uuid

- README.md
- auth-methods/api_key_auth.go
- auth-methods/auth_methods.go
- bindings/binding.go
- config.template
- config/config.go
- config/config_test.go
- config/configuration-test-files/test-conf.json
- docs/swagger.yml
- docs/v1/auth_certificate.md
- handlers/certificate_handlers.go
- handlers/certificate_handlers_test.go
- mapX509/map_x509.go
- mapX509/map_x509_test.go
- routing/routing.go
- servicetypes/service_type.go
- servicetypes/service_type_test.go
Provided a x509 certificate with the request, it will map the dn to a token for the specified service type
> ARGO-1165 X509 API Call

- utils/utils.go
- utils/utils_test.go
For later use in the project we will need a generic Setter method in order to avoid populating our interfaces with setter methods.
The problem is that we need our fields to be Exported in the structs that implement an interface so we can use the json marshal/unmarshal but we will also need setters to manipulate fields.Since we pass around interfaces and not concrete types, we will ahve to polute our interfaces with setters.
> ARGO-1312 Add utils method that sets a value to field given its name

- auth/certificate_test.go
- bindings/binding.go
- bindings/binding_test.go
- docs/swagger.yml
- docs/v1/docs/api_bindings.md
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- handlers/certificate_handlers.go
- handlers/certificate_handlers_test.go
- routing/routing.go
- stores/mock.go
- stores/models.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Apply the following changes to the binding structure:
1) Rename the **dn** field to **auth_identifier**
2) Add an extra field, **auth_type** that declares the type of the auth identifier
For example, if we provide a certificate's **dn** to the **auth_identifier field**, we should declare its **auth_type** as **x509**
The permitted **auth_types** a binding can have, are determined by the supported auth types of the service it belongs to(service_uuid)
Also refactor internal methods to use these extra fields, update swagger and mkdocks
> ARGO-1740 Change binding structure to be more generic

- authmethods/api_key_auth_test.go
- authmethods/authmethods.go
- authmethods/authmethods_test.go
- authmethods/headers_auth.go
- authmethods/headers_auth_test.go
- bindings/binding_test.go
- config.json
- docs/swagger.yml
- docs/v1/docs/api_authmethods.md
- handlers/authmethods_handlers_test.go
- handlers/binding_handlers_test.go
- handlers/service_type_handlers_test.go
- servicetypes/service_type_test.go
- stores/mock.go
- stores/models.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Create a new AuthMethod implementation called HeadersAuthMethod that allows the user to declare various headers that will be used as is when authn has to interact with the respective service type. 
Format:
{
"headers": {
"header-1": "value-1",
"header-2": "value-2"
},
"host": "127.0.0.1",
"port": 9000
}
> ARGO-1737 Add support for headers auth method

- bin/argo-api-authn-scripts/ams-create-users-cloud-info.py
- bin/argo-api-authn-scripts/ams-create-users-gocdb.py
Update the two user creation scripts to now use the projects: members add API Call, in order to create the respective ams users which require project admin access, instead of the general /v1/users create which required service admin access.
> ARGO-2331 Authn user creation scripts should use project admin tokens

- bindings/binding.go
- bindings/binding_test.go
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- stores/mock.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Update the internal functions of the service to be able to handle binding name uniqueness. This functionality is needed in order to be able to target bindings with other info(name) rather than uuid.
The two affected API calls are BindingsCreate and BindingsUpdate.
> ARGO-2493 Binding name should be unique

- bindings/binding.go
- bindings/binding_test.go
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- postman/authn_ci-cd_tests.postman_collection.json
- routing/routing.go
- stores/mock.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Update the BindingCreate api route to include the binding's name in the URL instead of the request body.
New API route would be - /v1/bindings/{binding-name}
> ARGO-2494 Modify the BindingCreate API route to include name in the path

- bindings/binding.go
- bindings/binding_test.go
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- postman/authn_ci-cd_tests.postman_collection.json
- routing/routing.go
- stores/mock.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Update the BindingsListOne api call to allow the query of bindings based on the provided name on the URL instead of the uuid.
New route would be GET /v1/bindings/{binding-name} instead of /v1/bindings/{binding-uuid}
> ARGO-2495 Bindings:ListOne API Call should accept name url path parameter

- bindings/binding.go
- bindings/binding_test.go
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- postman/authn_ci-cd_tests.postman_collection.json
- routing/routing.go
- stores/mock.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Update the BindingUpdate api call to allow the update of bindings based on the provided name on the URL instead of the uuid.
New route would be PUT /v1/bindings/{binding-name} instead of /v1/bindings/{binding-uuid}
> ARGo-2501 Modify the BindingUpdate API route to include name in the path

- bin/argo-api-authn-scripts/ams-create-users-cloud-info.py
- bin/argo-api-authn-scripts/ams-create-users-gocdb.py
- bindings/binding.go
- bindings/binding_test.go
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- postman/authn_ci-cd_tests.postman_collection.json
- routing/routing.go
- stores/mock.go
- stores/mongo.go
- stores/store.go
- stores/store_test.go
Update Authn scripts to check for possible DN updates when loading data from gocdb. Everytime a binging-user is found to be already existing, the scripts should retrieve the binding from authn and check if its DN has changed compared to the gocdb latest entry.
> ARGO-2466 Update authn scripts to handle DN changes

- docs/swagger.yml
- docs/v1/docs/api_bindings.md
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- routing/routing.go
Update the DeleteBinding API Route to now be able to target bindings for deletion through their name instead of their UUID.
new API route: DELETE /v1/bindings/{name} instead of /v1/bindings/{uuid}
Also, update swagger docs and mkdocs with all the needed changes.
> ARGO-2502 argo-api-authn: Modify the BindingDelete API route to include name in the path

- README.md
- conf/argo-api-authn-config.template
- config.json
- config/config.go
- config/config_test.go
- config/configuration-test-files/test-conf.json
- main.go
Provide a new configuration parameter **syslog_enabled**(true|false) to control the activation of direct syslog logging.
Making it a boolean will benefit us immediately when the new binary is deployed without having to add an extra configuration field to the authn installations.
> ARGO-2557 Make syslog logging configurable for AuthN

- argo-api-authn.spec
Release containing 1 feature and 1 bug fix.
- Make syslog configurable
- Fix a nil pointer bug while fetching cert's CRL
> ARGO-2730 Production release for authn 0.1.5

- bin/argo-api-authn-scripts/ams-create-users-cloud-info.py
- bin/argo-api-authn-scripts/ams-create-users-gocdb.py
- docs/swagger.yml
- docs/v1/docs/api_bindings.md
- handlers/binding_handlers.go
- handlers/binding_handlers_test.go
- routing/routing.go
Reorganizing the process of user and binding creation by always checking if the given DN already corresponds to an existing binding.
if that's the case, we retrieve the binding that uses the DN and treat it as the binding/user for this specific iteration.That means that instead of creating a new user, we use the already existing binding's name(which maps to a user in ams aswell) and we perform all AMS actions(add to project, add to topic acl etc) with the existing binding's name.
Example:
service1-host-1 and service2-host-1 use the same DN(test-dn).
service1-host-1 with test-dn will be normally created with the corresponding binding and ams user(service-1-host-1-username) and it is assigned to topic service-1-topic.
When the time comes for service2-host-1 to get registered and be assigned …
> ARGO-3102 authn: Update scripts to handle same DN under multiple endpoints

- argo-api-authn.spec
- auth/revoke.go
- auth/revoke_test.go
- bindings/binding.go
- config/config.go
- docs/swagger.yml
- docs/v1/docs/api_health.md
- docs/v1/docs/api_version.md
- docs/v1/mkdocs.yml
- handlers/authmethods_handlers_test.go
- handlers/binding_handlers_test.go
- handlers/generic_handlers.go
- handlers/generic_handlers_test.go
- handlers/service_type_handlers_test.go
- main.go
- routing/routing.go
- servicetypes/service_type.go
- stores/mongo.go
- utils/consts.go
- utils/consts_test.go
- utils/utils.go
- version/version.go
Add 2 new api calls
1) GET @ /v1/version that returns build,env, etc info sbout the service.The release information is hidden behind authentication
2) GET @ /v1/health which just acts as a ping
Few modification to the spec file in order to change the way we build the binary.Add security options and some extra data for the version api call
> AM-39 Authn Improvements

- bin/argo-api-authn-scripts/ams-create-users-cloud-info.py
- bin/argo-api-authn-scripts/ams-create-users-gocdb.py
- bin/requirements.txt
- setup.py
Since we want to use our scripts with non-service admins tokens, we needed to also update the user creation to utilize the project member API instead of the global user member API which is only accessible to service admins.
> AM-315 Update user creations scripts to use ams library projects:createUser functionality

- README.md
- conf/argo-api-authn-config.template
- config.json
- config/config.go
- config/config_test.go
- config/configuration-test-files/test-conf.json
- main.go
Since authn is directly exposed to the internet without any proxy in front of it, it needs a better configured https server.
Also the last couple months we have encountered the below issue a few times which is an indicator of leaked resources.
argo_api_authn: 2023/09/12 03:44:55 http: Accept error: accept tcp [::]:8443: accept4: too many open files; retrying in 1s
https://blog.cloudflare.com/exposing-go-on-the-internet/
> AM-335 authn: Configure https server connection timeouts

- argo-api-authn.spec
- version/version.go
AM-332 authn: Keep track of certificates that do not include IP SAN
AM-335 authn: Configure https server connection timeouts
AM-331 authn: Use the official mongodb driver
AM-325 authn:Introduce trace id identifier in logs
> New Release 1.1.0

- argo-api-authn.spec
- version/version.go
AM-330 authn: Integration tests for mongo 5.0 and mgo driver
AM-39 Enable again health check & version api calls
Update authn_ci-cd_tests.postman_collection.json
AM-343 Improper handling of errors during Fetch CRL functionality
AM-41 Authn upgrade to go 1.19
> New release 1.2.0

- argo-api-authn.spec
- version/version.go
AM-349 authn: Avoid using x509 v2 CRL parsing
> New version 1.3.0

- argo-api-authn.spec
- version/version.go
**New features/Enchantments**
- AM-356 Authn Compatibility with mongo 6
- AM-354 authn: Upgrade to Golang version 1.21.6
**Fixes**
- AM-354 FetchCrl should still use deprecated standard
> New Release 1.4.0
