ARGOeu/argo-api-authn

stores/mock.go
stores/models.go
stores/mongo.go
stores/store.go
stores/store_test.go

Functionality and Tests ready.
This commit includes how the interfacing with any datastore should happen, and the specific case of
mongo.

ARGO-1171 Database Interface with some basic functionality

---

auth/certificate.go
docs/swagger.yml
docs/v1/api_errors.md
docs/v1/api_services.md
handlers/generic_handlers.go
handlers/service_handlers.go
handlers/service_handlers_test.go
main.go
routing/routing.go
services/service.go
services/service_test.go
stores/mock.go
stores/models.go
stores/mongo.go
stores/store.go
stores/store_test.go
utils/api_errors.go
utils/api_errors_test.go
utils/consts.go
utils/consts_test.go
utils/response.go
utils/utils.go
utils/utils_test.go

Functionality Ready
Testing Ready
Need to add more documentation, and probably start a swagger file as well

ARGO-1174 API CALL - Create Service

---

docs/swagger.yml
docs/v1/api_errors.md
docs/v1/api_services.md
handlers/service_handlers.go
handlers/service_handlers_test.go
routing/routing.go
services/service.go
services/service_test.go
stores/mock.go
stores/mongo.go
stores/store_test.go
utils/api_errors.go
utils/api_errors_test.go
utils/response.go

Functionality ready.
Testing ready.
Docs and swagger updated

ARGO-1176 API CALL - Get Service(s)

---

.gitignore
auth-methods/api_key_auth.go
auth-methods/api_key_auth_test.go
auth-methods/auth_methods.go
docs/swagger.yml
docs/v1/api_auth_methods.md
handlers/auth_method_handlers.go
handlers/auth_method_handlers_test.go
routing/routing.go
services/service.go
services/service_test.go
stores/mock.go
stores/mongo.go
stores/store.go
stores/store_test.go

Functionality Ready
Tests ready
docs ready
swagger ready

ARGO-1183 API CALL - Get Auth method(s)

---

auth-methods/api_key_auth.go
auth-methods/api_key_auth_test.go
auth-methods/auth_methods.go
docs/swagger.yml
docs/v1/api_auth_methods.md
handlers/auth_method_handlers.go
handlers/auth_method_handlers_test.go
routing/routing.go
stores/mock.go
stores/mongo.go
stores/store.go
stores/store_test.go
utils/api_errors.go
utils/api_errors_test.go

Functionality ready
Tests ready
Docs ready
Swagger ready

ARGO-1182 API CALL - Create Auth method

---

docs/swagger.yml
docs/v1/api_service_types.md
handlers/auth_method_handlers.go
handlers/auth_method_handlers_test.go
handlers/service_type_handlers.go
handlers/service_type_handlers_test.go
routing/routing.go
servicetypes/service_type.go
servicetypes/service_type_test.go
stores/mock.go
stores/models.go
stores/mongo.go
stores/store.go
stores/store_test.go

Refactored service to service type, and updated tests, docs and swagger.

ARGO-1217 Change service to service type

---

bindings/binding.go
bindings/binding_test.go
docs/swagger.yml
docs/v1/api_bindings.md
handlers/auth_method_handlers_test.go
handlers/binding_handlers.go
handlers/binding_handlers_test.go
routing/routing.go
servicetypes/service_type_test.go
stores/mock.go
stores/models.go
stores/mongo.go
stores/store.go
stores/store_test.go

Create operation for bindings entity
tests ready, docs and swagger updated

ARGO-1211 API CALL - Create Binding

---

auth-methods/auth_methods.go
handlers/auth_method_handlers.go
handlers/auth_method_handlers_test.go
stores/mongo.go

Fixed bug, where List All Auth methods would return "null" instead of [].

Authm list fix

---

handlers/service_type_handlers_test.go
servicetypes/service_type.go
servicetypes/service_type_test.go

Fixed bug in List All Service types, that returned "null" instead of [] when the list was empty

Service types list fix

---

bindings/binding.go
bindings/binding_test.go
docs/swagger.yml
docs/v1/api_bindings.md
stores/mock.go
stores/models.go
stores/mongo.go
stores/store.go
stores/store_test.go

Assign a UUID to a binding upon creation.

Create binding UUID

---

bindings/binding.go
bindings/binding_test.go
docs/swagger.yml
docs/v1/api_bindings.md
handlers/binding_handlers.go
handlers/binding_handlers_test.go
routing/routing.go

Update binding functionality provided its UUID.
Updates tests, docs, swagger as well.

ARGO-1213 API CALL - Update Binding

---

.gitignore
bindings/binding.go
bindings/binding_test.go
docs/swagger.yml
docs/v1/api_bindings.md
docs/v1/mkdocs.yml
handlers/binding_handlers.go
handlers/binding_handlers_test.go
routing/routing.go
stores/mock.go
stores/mongo.go
stores/store.go
stores/store_test.go

Delete binding functionality, given its UUID.
tests, docs, swagger updated aswell.

 ARGO-1214 API CALL - Delete Binding

---

docs/swagger.yml
docs/v1/api_service_types.md
handlers/service_type_handlers.go
handlers/service_type_handlers_test.go
routing/routing.go
servicetypes/service_type.go
servicetypes/service_type_test.go
stores/mock.go
stores/mongo.go
stores/store.go
stores/store_test.go

Service type update functionality.
Tests, docs, swagger updated as well.
Also updated service-type-create to check for empty host list

Service type update

---

argo-api-authn.spec

ARGO-1463 argo-api-authn moderate severity security vulnerability regarding requests library

address a minor security vulnerability 

---

argo-api-authn.spec

Updated [release notes]( https://docs.google.com/document/d/1uEO1FiCxAlTRtg4FykJlLoyMY-Kscn6HbFrV8IYuOFY/edit#heading=h.lk3fv0f5ge5n)

ARGO-2376 Add a new release to argo-authN

---

auth/revoke.go
auth/revoke_test.go

- Better pointer handling around the FetchCRL functionality
- Improve logging during the FetchCRL

ARGO-2652 Authn FetchCRL nil pointer bug

---

setup.py

Update python-ldap to version 3.4.0

Update python-ldap to version 3.4.0

---

bin/argo-api-authn-scripts/ams-create-users-cloud-info.py
bin/argo-api-authn-scripts/ams-create-users-gocdb.py
bin/requirements.txt
setup.py

Upgrade script dependencies to require ams library 0.5.9
The introduction of 0.5.9 brings support for user management.
The introduction of the new ams library , changes the scripts in the following areas:
- Replace the user creation functionality from raw requests to the usage of the ams library
- Replace the project member add functionality from raw requests to the usage of the ams library
- Replace the user retrieval functionality through the project members api call to the usage of the ams library
- Replace topic and subscription creation and ACL modifications from raw requests to the usage of the ams library
Some minor improvements to logging as well.

AM-232 authn: update user creation scripts to use ams-library 0.5.9

---

argo-api-authn.spec

**New features/Enchantments**
- AM-232 authn: update user creation scripts to use ams-library 0.5.9
- AM-231 Authn transition to usage of headers auth method for ams
- Allow // in literal string when escaping commas
- Update gocdb scripts to escape commas inside RDNs
- AM-103: Upgrade TLS version
- AM-77: authn scripts: service endpoint should be in production as well
- AM-9: authn: All resources should include an updated_on field
- Update python-ldap version to 3.4.0

New release 1.0.0

---

Jenkinsfile

update Jenkins file environment with git user details

update Jenkins file environment with git user details

---

.github/workflows/docs.yml

Fix docs deployment through gh actions

Fix docs deployment through gh actions
